### ISSUE TITLE
Node Exporter Full 0.16 problem when node_exporter is on different ports

### ISSUE THREAD

**Issue by stuvie** [rfrail3/grafana-dashboards#11]
hi Ricardo, first of all - thank you for this excellent dashboard.

On my servers, some of the node_exporters are on port 9100 and some are on port 80.
I discovered that when I use the Host dropdown to select a host where the metrics are on port 80 
that the dashboards are all empty (no data). I enabled the port dropdown with the following change:

```
19505c19505
<         "hide": 2,
---
>         "hide": 0,
```

When I do that, and select port 80 from the dropdown, then the dashboard charts get populated.
Is this an issue with the regex on line 19513 of the json file?
We basically need the port to track the host appropriately.

here is the relevant section of my prometheus.yml - you can scrape my URLs to test

```
  # node_exporter metrics from various servers
  - job_name: node
    scrape_interval: 60s
    static_configs:
      - targets:
        - localhost:9100

      - targets:
        - devops.fywss.com:80
        - thrash.fywss.com:80
        - home.fywss.com:80
```

Cheers
Steve
