### ISSUE TITLE
How to use with multiple scrape_configs?

### ISSUE THREAD

**Issue by tholu** [rfrail3/grafana-dashboards#23]
My `prometheus.yml` looks like this:

```
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
  - job_name: 'node'

    # Override the global default and scrape targets from this job every 10 seconds.
    scrape_interval: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
        - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'servers'
    static_configs:
        - targets: ['server1','server2']
          labels:
            group: 'production'
```

When I import the dashboard, I can only select the Prometheus node itself. How can I view `server1` and `server2` stats with this dashboard?
