### ISSUE TITLE
Nothing loads on fresh install

### ISSUE THREAD

**Issue by johnpena** [rfrail3/grafana-dashboards#55]
On a fresh install, no metrics load and none of the dropdowns work.

I'm using the following versions:

```
node_exporter, version 0.18.1 (branch: , revision: )
prometheus, version 2.18.1 (branch: non-git, revision: non-git)
Grafana version 7.0.0
```

My prometheus.yml is very simple:

```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
```

I've confirmed there are no issues between Prometheus/Grafana/node_exporter that are readily apparent - I'm able to create charts in Grafana that are in Prometheus and from node_exporter. 

Attaching a screenshot of what I see. 

![Screen Shot 2020-05-22 at 10 29 48 AM](https://user-images.githubusercontent.com/43687/82678367-58adb900-9bfe-11ea-9f82-aee40948ab64.png)
