### ISSUE TITLE
HAProxy Query Params Outdated

### ISSUE THREAD

**Issue by lz006** [rfrail3/grafana-dashboards#62]
HI, thanks for your amazing Dashboard.
We use it for our HAProxy Installation. Unfortunately it seems as several metric names must have changed. Therefor we had to compensate it via following config:

``` yaml
    metric_relabel_configs:
    - source_labels: 
        - __name__
        - proxy
      target_label: frontend
      action: replace
      regex: (haproxy_frontend_.*);(.*)
      replacement: ${2}
    - source_labels:
        - __name__
        - proxy
      target_label: backend
      action: replace
      regex: (haproxy_backend_.*);(.*)
      replacement: ${2}
    - source_labels:
        - __name__
        - proxy
      target_label: backend
      action: replace
      regex: (haproxy_server_.*);(.*)
      replacement: ${2}
    - source_labels:
        - __name__
      target_label: __name__
      regex: haproxy_process_jobs
      replacement: haproxy_up
    - source_labels:
        - __name__
      target_label: __name__
      regex: haproxy_backend_status
      replacement: haproxy_backend_up
    - source_labels:
        - __name__
      target_label: __name__
      regex: haproxy_server_connection_attempts_total
      replacement: haproxy_server_connections_total
    - source_labels:
        - __name__
      target_label: __name__
      regex: haproxy_server_status
      replacement: haproxy_server_up
    - regex: proxy
      action: labeldrop
```

Without this workaround your Dashboard doesn't even find any host, backend and frontends.Main reason is, that HAProxys' built in prom exporter labels "frontend" and "backend" as "proxy".

Despite relabeling I wasn't to provide a replacement for:
- haproxy_server_current_session_rate
- haproxy_server_check_duration_milliseconds (-> now called "haproxy_server_check_duration_seconds")

thank you!
